// Generated by CoffeeScript 1.6.1
(function() {
  var Wamp, graphData, i, setup, _i;

  graphData = [];

  for (i = _i = 1; _i <= 10; i = ++_i) {
    graphData.push(new TimeSeries);
  }

  Wamp = (function() {

    function Wamp() {
      var _this = this;
      ab.connect("ws://localhost:9000", function(session) {
        console.log("Connected");
        _this.session = session;
        return _this.session.subscribe("http://coding-reality.de/tsd-event", _this.onEvent);
      }, function(code, reason) {
        return console.log("Fail: " + code + ", " + reason);
      });
    }

    Wamp.prototype.onEvent = function(topicUri, event) {
      console.log(topicUri);
      console.log(event);
      return graphData[event.id - 1].append(event.timestamp, event.data);
    };

    return Wamp;

  })();

  setup = function() {
    var graph, graphs, id, _j, _results;
    graphs = [];
    _results = [];
    for (id = _j = 1; _j <= 10; id = ++_j) {
      graph = new SmoothieChart;
      graph.streamTo(document.getElementById("graph_" + id), 100);
      _results.push(graph.addTimeSeries(graphData[id]));
    }
    return _results;
  };

  window.onload = function() {
    var wamp;
    wamp = new Wamp;
    return setup();
  };

}).call(this);
