// Generated by CoffeeScript 1.6.1
(function() {
  var Wamp, graph1Data, setup;

  graph1Data = new TimeSeries;

  Wamp = (function() {

    function Wamp() {
      var _this = this;
      ab.connect("ws://localhost:9000", function(session) {
        console.log("Connected");
        _this.session = session;
        return _this.session.subscribe("http://coding-reality.de/tsd-event", _this.onEvent);
      }, function(code, reason) {
        return console.log("Fail: " + code + ", " + reason);
      });
    }

    Wamp.prototype.onEvent = function(topicUri, event) {
      console.log(topicUri);
      console.log(event);
      return graph1Data.append(new Date().getTime(), event);
    };

    return Wamp;

  })();

  setup = function() {
    var graph1;
    graph1 = new SmoothieChart;
    graph1.streamTo(document.getElementById("graph1"), 100);
    setInterval((function() {}), 100);
    return graph1.addTimeSeries(graph1Data);
  };

  window.onload = function() {
    var wamp;
    wamp = new Wamp;
    return setup();
  };

}).call(this);
